### ISSUE TITLE
typo in sample.py

### ISSUE THREAD

**Issue by yuta100101** [m3dev/cookiecutter-gokart#4]
### What I did:  
1. make gokart project following the tutorial in [gokart documents](https://gokart.readthedocs.io/en/latest/tutorial.html#make-gokart-project)
2. run `Sample` task

### What happened:
ModuleNotFoundError like the following
```
hoge\gokart\example> python main.py gokart_example.Sample --local-scheduler
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    import gokart_example  File "hoge\gokart\example\gokart_example\__init__.py", line 1, in <module>
    from gokart_example.model.sample import Sample
  File "hoge\gokart\example\gokart_example\model\sample.py", line 3, in <module>
    from gokart_example.utils.templete import GokartTask
ModuleNotFoundError: No module named 'gokart_example.utils.templete'
```

### What To Do:
Modify the name of the module you are importing in `{{cookiecutter.package_name}}/model/sample.py `.
This is probably due to the last commit (https://github.com/m3dev/cookiecutter-gokart/commit/d673285c7ea7ae7d23ff72cc6f3ffeee2136f5f6).

```py
# before
from {{cookiecutter.package_name}}.utils.templete import GokartTask 

# after
from {{cookiecutter.package_name}}.utils.template import GokartTask 
```

**Comment by hirosassa** [comment]
@yuta100101 Thank you for your good suggestion!
